# Generated by Django 2.1.5 on 2021-01-19 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20210119_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_apprenticeship',
            name='companyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Apprenticeship'),
        ),
    ]
