# Generated by Django 2.1.5 on 2021-01-20 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_merge_20210120_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_apprenticeship',
            name='companyName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rango.Company'),
        ),
    ]
